### ISSUE TITLE
Android bottom bar color is not the same as the background color

### ISSUE THREAD

**Issue by bdlukaa** [presence-app/focused_menu#1]
![photo5154847666402863945](https://user-images.githubusercontent.com/45696119/151181189-2fdfb207-cb67-4418-97be-7c5eb279712d.jpg)

**Comment by iosephmagno** [comment]
The worst part is that navbar stays over the screen which makes impossible to really fix this issue

**Comment by iosephmagno** [comment]
![C22FC79E-4C0C-469F-BC99-0453B1CC8F2D](https://user-images.githubusercontent.com/83366073/151182243-b6371db2-df16-4a09-9a27-3446965269a6.png)

**Comment by bdlukaa** [comment]
We can use `AnnotatedRegion` to set the desired color!

**Comment by iosephmagno** [comment]
Yes but you won’t have background overlay. A possible workaround would be remove transparency, use a plain color and use it also for the navbar color

**Comment by iosephmagno** [comment]
What whatsapp does?
